### PR TITLE
support TargetFrameworkVersion for MSBuild

### PR DESCRIPTION
**Pull request by Thanood**
Hi!
I needed to support multi-target build with pvc, so I added an argument for targetFrameworkVersion. :-)

### CODE REVIEW

**Comment by stirno** [comment]
Great addition.. It would seem our differing opinions on whitespace have made the diff a bit larger than necessary as of that last commit. Can you clean that up and squash the commits so we can merge? Thanks!

**Comment by Thanood** [comment]
Strange, I've set git to commit unix-style newlines and there is still crlf..

**Comment by Thanood** [comment]
Should be better now.. :-)

**Comment by stirno** [comment]
Thanks a lot for the work, as you can see I merged it in. I'll push it to NuGet tomorrow morning, thanks again @Thanood!

**Comment by Thanood** [comment]
Great, thanks. I'm glad I could contribute. :-)

**Pull request merged**
